name: "JDK setup"
description: "Setup JDK"

inputs:
  jdk-version:
    description: 'The jdk version to use'
    default: '15'
    required: false
  jdk-distribution:
    description: 'The jdk distribution to use'
    default: 'adopt'
    required: false
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.mvn-cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: ${{ inputs.jdk-distribution }}

    - name: Cache local Maven repository
      id: mvn-cache
      uses: actions/cache@v2œ
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
