name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: rbkmoney/action-autotag@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
